### ISSUE TITLE
pretrain in defense

### ISSUE THREAD

**Issue by programehr** [ain-soph/trojanzoo#114]
Hi,
What's the use of pre-train in defense, please?

Thanks.

https://github.com/ain-soph/trojanzoo/blob/caad6edeaefa9cf0f9f3018454dc367df6494ec4/examples/backdoor_defense.py#L3

**Comment by ain-soph** [comment]
It's unnecessary because the model saved by previous attack is loaded. 

I'll consider removing it to make things clean.

You may close this issue if you have no further concern.

https://github.com/ain-soph/trojanzoo/blob/caad6edeaefa9cf0f9f3018454dc367df6494ec4/trojanvision/defenses/abstract.py#L53-L56

**Comment by programehr** [comment]
Thank you. I'll close it.

**Comment by programehr** [comment]
> It's unnecessary because the model saved by previous attack is loaded. You can just remove `--pretrained` in your command.
> 
> I'll consider removing it to make things clean.
> 
> You may close this issue if you have no further concern.
> 
> https://github.com/ain-soph/trojanzoo/blob/caad6edeaefa9cf0f9f3018454dc367df6494ec4/trojanvision/defenses/abstract.py#L53-L56

Hello again,

Excuse me, but I think it does have an effect. It loads the (possibly trojaned) model only if you specify the pre-train option. Otherwise, it will create a model from scratch.

Am I right?

**Comment by ain-soph** [comment]
No, —pretrained loads the clean pretrained model at model initialization, while defense.detect loads the previously saved attack result model.

if —original is claimed, then defense.detect will not load the attack model.

**Comment by ain-soph** [comment]
I’ll close this issue if there is no further question,
