### ISSUE TITLE
ABS not detecting Badnet

### ISSUE THREAD

**Issue by programehr** [ain-soph/trojanzoo#128]
Hi,
I've run Badnet attack, followed by ABS defense (with default settings). From the results, it seems like ABS cannot detect the attack, which is weird.

Specifically, this is the final result:
```
Score:  [7.156167772364617, 9.457871842956543, 4.543633675146103, 7.217127031528951, 5.883398698425293, 10.027698394012452, 10.763735179138184, 9.409244415664674, 9.147680532836914, 7.1922257972240455]
Score MAD:  tensor([0.0213, 0.7829, 0.9341, 0.0000, 0.4660, 0.9819, 1.2391, 0.7659, 0.6745,
        0.0087])
```

Does anybody have an idea why? Or maybe I am misinterpreting the results?

```sh
python3.9 ./examples/train.py --verbose 1 --dataset cifar10 --model resnet18_comp --lr_scheduler --cutout --grad_clip 5.0 --save --device cuda > train.txt

python3.9 ./examples/backdoor_attack.py --verbose 1 --pretrain --validate_interval 1 --dataset cifar10 --model resnet18_comp --attack badnet --random_init --epoch 50 --lr 0.01 --save --device cuda > test2_.txt

 python3.9 ./examples/backdoor_defense.py --verbose 1 --pretrain --validate_interval 1 --dataset cifar10 --model resnet18_comp --attack badnet --defense abs --random_init --device cuda > defens_abs_attack_badnet.txt
```
Output of the above commands:

[train.txt](https://github.com/ain-soph/trojanzoo/files/8250838/train.txt)
[test2_.txt](https://github.com/ain-soph/trojanzoo/files/8250842/test2_.txt)
[defens_abs_attack_badnet.txt](https://github.com/ain-soph/trojanzoo/files/8250857/defens_abs_attack_badnet.txt)

**Comment by ain-soph** [comment]
Sorry for not replying in time. In hospital for a few days. Will take a look tonight.

From provided commands and logs, I find several suspicious points, that might be helpful.

1. You are using old version trojanzoo. ‘—pretrain’ is replaced by ‘—pretrained’ in new version to keep consistent with torchvision. And new version trojanzoo supports python 3.10 only.  

    I’ve reimplemented abs in recent version and tested. It should be working fine. I’ll later add a log file.
3. In defense log, the clean acc listed in attack and defense summary is 76, which is strange. It should be consistent with training result 96.

**Comment by ain-soph** [comment]
Here's the result.  
I just updated the print sentences to make it prettier.  

Note this implementation should be consistent with original author's code.  
While TrojanZoo paper's ABS result is actually my own implementation after reading the paper (Because the original authors didn't release their codes at that time). That implementation is more similar to Neural Cleanse and therefore its performance is good. But it should **NOT** be.

From the result, we can observe that class 0 (target class) has a 30% ASR watermark, while class 0 has a 40%.

![image](https://user-images.githubusercontent.com/13214530/158921557-839f0e0e-401b-417b-92a6-6a83467f2f57.png)

**Comment by programehr** [comment]
Hi, I hope you're fine now.
Thanks a lot for your time. I'm investigating the problem and will tell you the result.

**Comment by ain-soph** [comment]
I’ll finish the ABS docs soon. Hope that will help you.

**Comment by programehr** [comment]
> 2. In defense log, the clean acc listed in attack and defense summary is 76, which is strange. It should be consistent with training result 96.

I realized that the defense code first prints the summary, then the `detect` method of the defense class loads the trojaned model.

**Comment by ain-soph** [comment]
I've moved the model loading from `detect()` to `__init__()` 

https://github.com/ain-soph/trojanzoo/blob/2698c221a2662719d550cb47acc72e6da81ee544/trojanvision/defenses/abstract.py#L58-L61

**Comment by programehr** [comment]
Now it's OK for me, but just FWI, I ran it without --pretrain and faced a similar issue. I think that in this case, it uses a randomly initialized model at first and prints its summary.

Thank you for your time.

**Comment by ain-soph** [comment]
I'll close this issue if there is no further question.
