### ISSUE TITLE
cannot import name 'Callable' from 'collections' 

### ISSUE THREAD

**Issue by TheSunWillRise** [ain-soph/trojanzoo#129]
cannot import name 'Callable' from 'collections' 
for python==3.10

**Comment by ain-soph** [comment]
Are you using the codes in github repo?

The current released version is for python 3.9, which might still contains the deprecated sentence `from collections import Callable`

**Comment by ain-soph** [comment]
Please clone the repo and install it using `pip install -e .`

**Comment by TheSunWillRise** [comment]
That works, thank you
