### ISSUE TITLE
Useless --save of Attacks

### ISSUE THREAD

**Issue by EmmetWilliam** [ain-soph/trojanzoo#130]
It seems like the adjusted **[trojanzoo/utils/train.py](https://github.com/ain-soph/trojanzoo/blob/main/trojanzoo/utils/train.py)** goes wrong in `train()` when comparing between the `best_acc` and `cur_acc` to save the model.

`best_acc` will preserve the original clean ACC at the very beginning but the attack will decrease the ACC, and therefore the backdoored model will never be saved...QAQ

**Comment by ain-soph** [comment]
https://github.com/ain-soph/trojanzoo/blob/7d75287e378832e33c4f25f1713092b4d1f34c10/trojanvision/attacks/backdoor/badnet.py#L287

Sorry, the attack validate function should return asr as first parameter!

I’ll change it very soon,
