### ISSUE TITLE
resnet18 and resnet18_comp

### ISSUE THREAD

**Issue by rahulxie** [ain-soph/trojanzoo#134]
What is the difference between resnet18 and resnet18_comp?

**Comment by ain-soph** [comment]
https://ain-soph.github.io/trojanzoo/trojanvision/models/torchvision.html#trojanvision.models.ResNet

**Comment by rahulxie** [comment]
> https://ain-soph.github.io/trojanzoo/trojanvision/models/torchvision.html#trojanvision.models.ResNet

Thank you! I found this: "_comp reduces the first convolutional layer from kernel_size=7, stride=2, padding=3

to kernel_size=3, stride=1, padding=1, and removes the maxpool layer before block layers."
