### ISSUE TITLE
Some questions about installing

### ISSUE THREAD

**Issue by willu-x** [ain-soph/trojanzoo#152]
hello author!
   i met a few question when i try to use [trojanzoo]
1.
![image](https://user-images.githubusercontent.com/60807399/179944992-f5efea31-1044-44fc-b554-93d680d11dc5.png)
Are these 4 points all need to be done? Or just choose one to install?
2.
when i run `docker pull local0state/trojanzoo` or `docker pull ghcr.io/ain-soph/trojanzoo`,the error are 
![image](https://user-images.githubusercontent.com/60807399/179945635-29c08372-7cf9-49fa-befc-f2d50d5cc90a.png)
and
![image](https://user-images.githubusercontent.com/60807399/179945783-8335babf-117e-41ee-a5a4-06c0249558f9.png)
how can i solve them?
3.the command `conda install trojanzoo` shows 
![image](https://user-images.githubusercontent.com/60807399/179946152-b9da6b09-203d-4714-af48-f7e1a09dd942.png)
Do this cant install by conda?
4.the last question is when i run the quick_start
i use `python ./examples/train.py --color --verbose 1 --dataset cifar10 --model resnet18_comp --lr_scheduler --cutout --grad_clip 5.0 --save` and get 
![image](https://user-images.githubusercontent.com/60807399/179946782-25a6aae3-acaa-4b0b-b10e-c1130c127e46.png)
im hoping for your reply! thank you.

**Comment by ain-soph** [comment]
1. That seems to be your docker issue. Please try installing other docker containers to make sure it works.
2. conda install is not implemented yet.
3. According to your exception log, it seems to be your sklearn package issues. Please fix it.

**Comment by willu-x** [comment]
> 
Hello：
I tried one more time,when i use `python ./examples/train.py --color --verbose 1 --dataset cifar10 --model resnet18_comp --lr_scheduler --cutout --grad_clip 5.0 --save` Its shows thats `ModuleNotFoundError: No module named 'skimage'`，
like this：
![image](https://user-images.githubusercontent.com/60807399/180131468-de065780-6aa3-40a0-ae10-b458e3e12dc7.png)

When i try to install skimage ，the error is 
![image](https://user-images.githubusercontent.com/60807399/180131388-071db700-e757-40f8-ad78-076b11e12b8d.png)

Thank you for the reply.

**Comment by ain-soph** [comment]
https://scikit-image.org/docs/stable/install.html#install-via-pip


It's `pip install scikit-image` rather than `skimage`

**Comment by ain-soph** [comment]
It seems the current issue is not relevant to `trojanzoo` itself, so I'll close it.

If you have any issue about general python packages, feel free to contact me at rbp5354@psu.edu

**Comment by ain-soph** [comment]
Sorry for replying late that your email was detected as junk by my university email system.

Since you have already got the skimage installed, do you have the new error log for the script?
