### ISSUE TITLE
Question about experiment after pip install

### ISSUE THREAD

**Issue by CHR-ray** [ain-soph/trojanzoo#153]
After pip install, can I run your attack/defense outside your repo folder? eg. directly type 'python -m xxxx' in terminal in any other folder path. 

If it is possible, how to write the command in terminal and where those intermediate file would locate? (eg. pt file for weights saved during attack/defense, datasets used in your scripts, etc.)

**Comment by ain-soph** [comment]
Those things are in the configs. Please make sure you set things (eg, data_path) correctly.

You could modify user-level and workspace-level configs following  

https://ain-soph.github.io/trojanzoo/trojanzoo/configs.html  

https://ain-soph.github.io/trojanzoo/trojanvision/configs.html

**Comment by ain-soph** [comment]
Example config files https://github.com/ain-soph/trojanzoo/blob/main/trojanzoo/configs/dataset.yml

**Comment by CHR-ray** [comment]
Sorry to reply late. So after pip install, I should change the config file in the place that package pip installed?

**Comment by ain-soph** [comment]
No, you should follow the pattern of those files and make your own configs at user level or workspace level as illustrated in https://github.com/ain-soph/trojanzoo/issues/153#issuecomment-1199520076

**Comment by CHR-ray** [comment]
I think I understand, thank you.
