### ISSUE TITLE
Install newest version fail

### ISSUE THREAD

**Issue by CHR-ray** [ain-soph/trojanzoo#160]
Hello, 

When I try to install your repo (commit 955b021ec911b4102f6478c79170d5b481931fa2) to a new conda env (created without any other packages installed before) by 

```
git clone https://github.com/ain-soph/trojanzoo
pip install -e trojanzoo
```

I meet 
```
ERROR: Package 'trojanzoo' requires a different Python: 3.9.7 not in '>=3.10' 
```

I think maybe your requirements file are not self-consistent for this commit？

**Comment by ain-soph** [comment]
Clearly you are creating a env with python version 3.9.7 rather than >=3.10
