### ISSUE TITLE
RuntimeError: Dataset not found or corrupted. You can use download=True to download it

### ISSUE THREAD

**Issue by ArshadIram** [ain-soph/trojanzoo#163]
The project is downloaded successfully. 

git clone https://github.com/ain-soph/trojanzoo
pip install -e trojanzoo

When I run this command:

python ./examples/train.py --color --verbose 1 --dataset cifar10 --model resnet18_comp --lr_scheduler --cutout --grad_clip 5.0 --save

I am getting this error message:

![image](https://user-images.githubusercontent.com/50909488/189499244-f5adb3e1-4366-4712-a288-b1f5f2307839.png)

Why this import showing error:
import trojanvision
![image](https://user-images.githubusercontent.com/50909488/189499291-b59ccc03-fdb4-4980-ab75-61e8cbdef015.png)

**Comment by ain-soph** [comment]
Please use --download to download the dataset.

For the import error, please check your linter message for more information.

**Comment by ArshadIram** [comment]
Now I am getting SSL error:

![image](https://user-images.githubusercontent.com/50909488/189522834-4634b009-bcac-44cd-a5f6-ea893abf9b87.png)
 File "C:\Users\irama\anaconda3\envs\security\lib\site-packages\torchvision\datasets\utils.py", line 94, in _get_redirect_url

**Comment by ArshadIram** [comment]
how can I install torjanvision? Do I need to install seperately or this comes with torjanzoo ?

**Comment by ain-soph** [comment]
Please check your pytorch version to make sure it's up to date.  
You only need to install once with `pip install trojanzoo`

**Comment by ArshadIram** [comment]
![image](https://user-images.githubusercontent.com/50909488/189822949-f98d1d85-330a-4e9d-bc55-1e016e5a783c.png)
Here is my pytroch version.

**Comment by ain-soph** [comment]
The error is not in TrojanZoo package.

Please check if the following torchvision command could be normally executed to download CIFAR10 dataset:

`torchvision.datasets.CIFAR10(root='./', train=True, download=True)`

**Comment by ArshadIram** [comment]
No I am getting this error now: urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)>

I just updated python and updated torch for this code. 
It was working before for other projects.

**Comment by ain-soph** [comment]
`torchvision.datasets.CIFAR10(root='./', train=True, download=True)` is related to `torchvision` package and not relying on `trojanzoo` package. Maybe you can raise an issue in their repo.

**Comment by ArshadIram** [comment]
I solved this issue. However, I am still getting an import error "import trojanvision"

**Comment by ain-soph** [comment]
You need to provide enough information for the import error.
