### ISSUE TITLE
Clean label attack accuracy is wrong 

### ISSUE THREAD

**Issue by ArshadIram** [ain-soph/trojanzoo#164]
I am trying to reproduce the clean label backdoor attack and getting this accuracy 

![image](https://user-images.githubusercontent.com/50909488/190129544-96efb739-9173-410b-b986-4b41596aee7c.png)

**Comment by ain-soph** [comment]
clean label is a baseline that is expected to not work.

I guess you are referring to label consistent attack, which is work from Marty’s group.

**Comment by ArshadIram** [comment]
Yes, Label consistent attack. Could not understand Madry's group?

**Comment by ain-soph** [comment]
https://arxiv.org/abs/1912.02771


https://github.com/ain-soph/trojanzoo/blob/main/trojanvision/attacks/backdoor/clean_label/label_consistent.py

**Comment by ArshadIram** [comment]
Even refool attack success rate is very lower:

![image](https://user-images.githubusercontent.com/50909488/190355453-91fa0e98-63a5-4f8f-8e2a-ae03242f5b91.png)

**Comment by ain-soph** [comment]
That is recently changed in https://github.com/ain-soph/trojanzoo/commit/c2fd73e3e9380514f09020a93b8e216703a6a3ee for the mark alpha value.  
We believe it's expected to not work. If you find any solution to make it perform well, we may have a discussion on that.  

Here's my notes on Refool: https://ain-soph.github.io/trojanzoo/trojanvision/attacks/backdoor/clean_label.html#trojanvision.attacks.Refool
