### ISSUE TITLE
In new push model path is not working

### ISSUE THREAD

**Issue by ArshadIram** [ain-soph/trojanzoo#165]
FileNotFoundError: [Errno 2] No such file or directory: 'data\\model\\image\\cifar10\\resnet18_comp.pth'

**Comment by ain-soph** [comment]
Please provide enough information for the error. What kind of task are you running? Are you using example scripts?  

I assume you are running BadNet attack and trying to load a clean model that is previously pretrained by adding cmd parameter `--pretrained`. Then you shall run `./examples/train.py` first to train a model to save it there.

For the model path, you are using the default path in the package. You can always set your workspace config. For more details, please refer to the docs: https://ain-soph.github.io/trojanzoo/trojanvision/configs.html
