### ISSUE TITLE
badnet folder information 

### ISSUE THREAD

**Issue by ArshadIram** [ain-soph/trojanzoo#166]
![image](https://user-images.githubusercontent.com/50909488/192166853-a83b3681-644b-4c8e-b5e1-be674d8325d0.png)
I just want to know what this npy file contains?

**Comment by ain-soph** [comment]
https://github.com/ain-soph/trojanzoo/blob/1a2adf9f82d772642dffa9fe79af6784931d636f/trojanvision/attacks/abstract.py#L188-L195

**Comment by ArshadIram** [comment]
Hi, thanks for the quick response. Is it possible to access the poison dataset?
