### ISSUE TITLE
[Error] When I test Neural Cleanse i got a error

### ISSUE THREAD

**Issue by Ghifan** [ain-soph/trojanzoo#174]
I first git clone git clone https://github.com/ain-soph/trojanzoo.git

and run python ./examples/backdoor_defense.py --color --verbose 1 --pretrained --validate_interval 1 --dataset cifar10 --model resnet18_comp --attack badnet --defense neural_cleanse --mark_random_init --epochs 50 --lr 0.01

then i got the error:TypeError: unsupported operand type(s) for |: '_SpecialForm' and 'types.GenericAlias'

btw my python version is 3.8 should i change it to 3.1?

**Comment by ain-soph** [comment]
Yes, you should. Type annotation requires 3.9 and match clause requires 3.10

**Comment by Ghifan** [comment]
> 

ok,thank you
