### ISSUE TITLE
Is it possible to apply methods to graph?

### ISSUE THREAD

**Issue by WangHexie** [ain-soph/trojanzoo#175]
I have to implement dataset, model, attack method and defense method. Is subclassing subclass base class(Dataset, Model, Attack, Defense) sufficient  to run the code?  And is it possible to apply existing attack/defense method to my DIY model on graph?

**Comment by ain-soph** [comment]
Does "graph" here refers to "GNN"?

**Comment by WangHexie** [comment]
yes.

**Comment by ain-soph** [comment]
I'm afraid current "trojanvision" doesn't consider GNN, but you may find "trojanzoo" shall be a generic thing.

If you want, you may use "trojanzoo" as a start. But it might take more effort than coding from scratch if you are not familiar with it.

**Comment by WangHexie** [comment]
Thanks for your reply. I thought some methods like randomized smooth would be task-agnostic. I looked through[ the relevant code](https://github.com/ain-soph/trojanzoo/blob/main/trojanvision/defenses/backdoor/attack_agnostic/randomized_smooth.py), it seems it really would take a lot of work to understand how the framework works.

**Comment by ain-soph** [comment]
You may want to check this part.

https://github.com/ain-soph/trojanzoo/blob/ec5281311b44fce9c82f98b96c0027d84ed7f08b/trojanzoo/models.py#L387-L395

**Comment by WangHexie** [comment]
Thanks a lot. I'm reading the source code now.
