### ISSUE TITLE
Input aware dynamic backdoor error

### ISSUE THREAD

**Issue by GorkaAbad** [ain-soph/trojanzoo#176]
Hi!,
I wanted to know if when using the ```--attack input_aware_dynamic``` I also should provide some ```mask ``` parameters.  I assume that I don't have to since the trigger should be included throughout the image.

I'm running this:
```python examples/backdoor_attack.py --color --verbose 1 --dataset cifar100 --model vgg11_bn --attack input_aware_dynamic --save --download --poison_percent 0.001 --epochs 100 --pretrained --output 1 --dataset_normalize --train_mask_epochs 1 --attack_dir res/```

But I keep getting this error in  /trojanvision/attacks/backdoor/dynamic/input_aware_dynamic.py", line 378, in attack:
```UnboundLocalError: local variable 'loss_div' referenced before assignment```

Thanks in advance.

**Comment by ain-soph** [comment]
Are you using the most up-to-date code?

**Comment by GorkaAbad** [comment]
Yes, I think so. I just installed the latest version from GitHub today.

**Comment by ain-soph** [comment]
Just commit a fix. Could you please try whether it works?

**Comment by GorkaAbad** [comment]
Thanks for the fast response. Yes, that problem its solved now.

**Comment by ain-soph** [comment]
Thanks for your report. The error is raised because of the low poison percent and there might be no poisoning data in a batch. I previously didn't take that into consideration.
