### ISSUE TITLE
problem about saving the intermediate results and config problem

### ISSUE THREAD

**Issue by andyclsr** [ain-soph/trojanzoo#185]
hi, your work is excellent but i encounter some problems.
first , i read similar problems https://github.com/ain-soph/trojanzoo/issues/153 and 
your https://ain-soph.github.io/trojanzoo/trojanvision/configs.html ,but  constructions about configs are hard to understand and the example you provide is limited like this : https://github.com/ain-soph/trojanzoo/blob/main/trojanzoo/configs/dataset.yml.

my problem is i don't know how to store intermediate results and i think it is my config problem
i do something like this : and for example attack.yml  is only " attack_dir: /data/attack/"
and my file structure:
![image](https://user-images.githubusercontent.com/69943589/229275498-2e88cc5a-59e4-424b-869a-b934fe2fe2fa.png)
my main.py :
![image](https://user-images.githubusercontent.com/69943589/229275602-3bc17bb8-9198-4fca-91b2-b7ea46ac5b55.png)
i still wonder about the use of config file and it seem like nothing was stored.
i hope you could give a concrete example about the use of it. thx anyway

**Comment by andyclsr** [comment]
can concretely tell me how to store the attacked model after this step:
![image](https://user-images.githubusercontent.com/69943589/229276574-854236ac-28d0-4560-a23c-6d949728ff27.png)

**Comment by ain-soph** [comment]
`attack_dir` sets the `folder_path` of `Attack` instance, which is `attack.folder_path`. This property is used in many places including saving method (see following)
https://github.com/ain-soph/trojanzoo/blob/1f417cc0da0c4ad0483a6f050f18930d0813f9e3/trojanvision/attacks/abstract.py#L110-L112

https://github.com/ain-soph/trojanzoo/blob/1f417cc0da0c4ad0483a6f050f18930d0813f9e3/trojanvision/attacks/abstract.py#L185-L192

The `save_fn` is passed to `model._train` method and used in 
https://github.com/ain-soph/trojanzoo/blob/1f417cc0da0c4ad0483a6f050f18930d0813f9e3/trojanzoo/utils/train.py#L201-L203

**Comment by andyclsr** [comment]
thank you every much for your generous explanations！
but i still wonder how to set intervals to save the model ? I don't see there are any parameters about the setting of the interval in the `save_fn` which it seems that I can't reach the number of epoch then in the `save_fn` i can't control the interval?
but it seems as long as `save` is True then it just save the model in the end but there aren't any setting of interval?

thank you in advance !

**Comment by ain-soph** [comment]
To control the interval to save models, use validate_interval parameter (command-line argument as well)

https://github.com/ain-soph/trojanzoo/blob/1f417cc0da0c4ad0483a6f050f18930d0813f9e3/trojanzoo/utils/train.py#L180

https://github.com/ain-soph/trojanzoo/blob/1f417cc0da0c4ad0483a6f050f18930d0813f9e3/trojanzoo/trainer.py#L123

**Comment by andyclsr** [comment]
> To control the interval to save models, use validate_interval parameter (command-line argument as well)
> 
> https://github.com/ain-soph/trojanzoo/blob/1f417cc0da0c4ad0483a6f050f18930d0813f9e3/trojanzoo/utils/train.py#L180
> 
> https://github.com/ain-soph/trojanzoo/blob/1f417cc0da0c4ad0483a6f050f18930d0813f9e3/trojanzoo/trainer.py#L123

what if i want to save multiple models? not just updating one model.

**Comment by ain-soph** [comment]
@andyclsr You can overload save_fn or pass your own save_fn to model._train in attack.attack

**Comment by andyclsr** [comment]
ok I know it. really thank you for your generous explanations! wish you a good day!
