### ISSUE TITLE
STRIP implementation doesn't match original codebase

### ISSUE THREAD

**Issue by kshitijsachan** [ain-soph/trojanzoo#188]
Your STRIP defense implementation seems reasonable (linearly mix benign and test inputs), but this is different from the official implementation from the STRIP repo, where they just add both images on top of each other. Not sure if this was intentional or not.

Trojanzoo implementation:
https://github.com/ain-soph/trojanzoo/blob/58d309b399024be62782b285e7cc8cede147bbc8/trojanvision/defenses/backdoor/input_filtering/strip.py#L74

[original STRIP implementation](https://github.com/garrisongys/STRIP/blob/master/STRIP_CIFAR10DeepArchit_Tb.ipynb):
```
def superimpose(background, overlay):
  added_image = cv2.addWeighted(background,1,overlay,1,0)
  return (added_image.reshape(32,32,3))
```

**Comment by ain-soph** [comment]
According to [opencv documents](https://docs.opencv.org/3.4/d5/dc4/tutorial_adding_images.html), I don't see any difference between the 2 implementations.
