### ISSUE TITLE
Attack saving and loading is not working

### ISSUE THREAD

**Issue by kshitijsachan** [ain-soph/trojanzoo#189]
It seems like a lot of the attacks don't have saving implemented correctly (e.g. trojannet). This is making it hard for me to run `backdoor_defense.py` because it first loads the attacked model.

**Comment by ain-soph** [comment]
Please provide more details so that I could support you better.  

Most backdoor attacks have default saving method implemented in the abstract class.
https://github.com/ain-soph/trojanzoo/blob/58d309b399024be62782b285e7cc8cede147bbc8/trojanvision/attacks/abstract.py#L185-L192
