### ISSUE TITLE
Comp version of networks

### ISSUE THREAD

**Issue by programehr** [ain-soph/trojanzoo#190]
Hi,

I was wondering what 'comp' means in the model names. Also, did you define the architecture or borrowed it from somewhere else?

Thanks.

**Comment by ain-soph** [comment]
Please check the docs:
https://ain-soph.github.io/trojanzoo/trojanvision/models/torchvision.html#trojanvision.models.ResNet

Almost all people use this variant version on CIFAR dataset for smaller resolution.

**Comment by programehr** [comment]
Thanks a lot!
