### ISSUE TITLE
Inconsistent return type in`validate_func`

### ISSUE THREAD

**Issue by hkunzhe** [ain-soph/trojanzoo#45]
**Describe the bug**
Traceback (most recent call last):
  File "/home/hkz/trojanzoo/backdoor_defense.py", line 41, in <module>
    defense.detect(**trainer)
  File "/home/hkz/trojanzoo/trojanvision/defenses/backdoor/fine_pruning.py", line 65, in detect
    self.prune(**kwargs)
  File "/home/hkz/trojanzoo/trojanvision/defenses/backdoor/fine_pruning.py", line 76, in prune
    _, target_acc, clean_acc = self.attack.validate_func()
ValueError: not enough values to unpack (expected 3, got 2)

**To Reproduce**
1. git clone the current repo and download the cifar10 dataset
2. mv backdoor_defense.py from `example` dir to the repo root
3. run the quick start example
`python backdoor_defense.py --verbose 1 --validate_interval 1 --dataset cifar10 --model resnetcomp18 --attack badnet --defense fine_pruning --random_init --epoch 50 --lr 0.01`

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/30763967/103767129-0b7e3a80-505b-11eb-80c1-2e53e8401da8.png)

**Desktop (please complete the following information):**
 - OS: ubuntu 18.04
 - Version git commit id 7478061

**Comment by ain-soph** [comment]
Yes. You are correct. I recently modified so many APIs in datasets and models, but haven't tested the usage in attack and defenses yet. I'm currently working on it right now.

**Comment by ain-soph** [comment]
Just a suggestion.  
You could use `python setup.py develop` to install the package so that you don't need to move files from `examples` to the root directory. And `develop` option won't copy files to `site-packages` so that you could make modification directly in the repo. 
And you may want to change the `numpy` version, as `==1.19.3` if to avoid a severe issue for 1.19.4 on windows. If you work on Ubuntu or MacOS, you could use the newest version of numpy for sure.

**Comment by hkunzhe** [comment]
> Just a suggestion.
> You could use `python setup.py develop` to install the package so that you don't need to move files from `examples` to the root directory. And `develop` option won't copy files to `site-packages` so that you could make modification directly in the repo.
> And you may want to change the `numpy` version requirements in `setup.cfg`, as `==1.19.3` is to avoid a severe issue for 1.19.4 on windows. If you work on Ubuntu or MacOS, you could use the newest version of numpy for sure.

Thanks for your suggestion. Trojanzoo is a great project!:+1:
