### ISSUE TITLE
There seems to be a small mistake in model.py

### ISSUE THREAD

**Issue by FuChong-cyber** [ain-soph/trojanzoo#52]
**(1)**
**Describe the bug**
There seems to be something wrong in the 298th line in model.py. Is the path correctly set?

**To Reproduce**
I tried to run this project with the command in the Quick Start:
_python train.py --verbose 1 --amp --dataset cifar10 --model resnetcomp18 --epoch 150 --lr 0.1 --lr_scheduler --lr_decay_step 50 --save_

Then I got an error when saving the model:
![image](https://user-images.githubusercontent.com/61871762/104147123-14c72880-5408-11eb-8613-f137c5cd4ffd.png)

I checked the code and change the 298th line in model.py:
from
_file_path = os.path.normpath(os.path.join(folder_path, self.name, suffix, '.pth'))_
to
_file_path = os.path.normpath(os.path.join(folder_path, suffix, self.name + '.pth'))_

Then the code ran normally and the model is saved at: _data\model\image\cifar10\resnetcomp18.pth_

I wonder whether I am doing the right thing? 

**Desktop (please complete the following information):**
 - OS: Windows 10

**(2)**
**Describe the bug**
I found another problem about path when running backdoor_attack.py.
Just run the second command in Quick Start and I got an error saying like "os.path.split() got wrong arguments".

Then I changed the 92nd line in badnets.py to fix this, form:
_mark_filename = os.path.split(self.mark.mark_path)_
to:
_mark_filename = os.path.split(self.mark.mark_path)[-1]_

Although the code ran normally, the files about attack seemed not correctly stored:
![image](https://user-images.githubusercontent.com/61871762/104149134-1ac10780-5410-11eb-887e-07c85b985ec5.png)

Could the authors tell me whether there is a better way to fix this?

**(3)**
**Describe the bug**
The command to run “IMC” in Quick Start seems to be not correct, should it be:
_python backdoor_attack.py --verbose **1** --pretrain --validate_interval 1 --amp --dataset cifar10 --model resnetcomp18 --attack imc --random_init --epoch 50 --lr 0.01 --save_ ?

Further more, I found I cannot run this command unless I change the 71st line in the trojannn.py:
from:
_self.pgd = PGD(alpha=self.neuron_lr, epsilon=1.0, iteration=self.neuron_epoch, output=0)_
to:
_self.pgd = PGD(alpha=self.neuron_lr, epsilon=1.0, iteration=self.neuron_epoch, output=0, model=self.model)_

**Comment by ain-soph** [comment]
Of course you’re doing the right thing. Sorry for the bugs. I haven’t fully tested...  
You can submit a PR, or I’ll fix it later.
