### ISSUE TITLE
'_ResNetcomp' object has no attribute 'preprocess'

### ISSUE THREAD

**Issue by cyqnn98** [ain-soph/trojanzoo#53]
**Describe the bug**
I was trying to run the ABS defense on a pretrained resnetcomp model. The following bug appeared:
![image](https://user-images.githubusercontent.com/61383989/108851975-fddb3f00-761f-11eb-8eb0-36f50e1df46a.png)
It seems that the preprocess method has not been defined in the model ResNetcomp or its parent classes.
Btw, I found a preprocess method defined in the activation_clustering defense. Does this method have any relationship with the process method called in resnet.py?

**Desktop (please complete the following information):**
 - OS: ubuntu
 - Browser chrome

**Comment by ain-soph** [comment]
It’s fixed in the last pull 2 days ago (fix normalize).
The API changes name from “preprocess” to “normalize”

**Comment by ain-soph** [comment]
Ah, sorry, I forgot to modify that in ResNet,

**Comment by cyqnn98** [comment]
> Ah, sorry, I forgot to modify that in ResNet,

Got it! Thanks!

**Comment by ain-soph** [comment]
> > Ah, sorry, I forgot to modify that in ResNet,
> 
> Got it! Thanks!

If you think it's fixed in the most recent push, you may close this issue.
