### ISSUE TITLE
Problem Installing TrojanZoo in Linux

### ISSUE THREAD

**Issue by haripriyaharikumar** [ain-soph/trojanzoo#56]
I have installed all the dependencies based on the requirements.txt file.
Then when I tried to install trojanzoo using:

pip install trojanzoo 
 It was showing this error

ERROR: Could not find a version that satisfies the requirement trojanzoo
ERROR: No matching distribution found for trojanzoo

I have installed all the libraries in the requirements.txt file, I am not sure why this is showing this error.

**Comment by ain-soph** [comment]
Have you tried clone the repo and run `python setup.py develop`?

**Comment by ain-soph** [comment]
And have you make sure your `python>=3.9.2` `pytorch>=1.8.1`?

**Comment by haripriyaharikumar** [comment]
> Have you tried clone the repo and run `python setup.py develop`?

not yet.

**Comment by haripriyaharikumar** [comment]
> Have you tried clone the repo and run `python setup.py develop`?

**Comment by haripriyaharikumar** [comment]
> And have you make sure your `python>=3.9.2` `pytorch>=1.8.1`?

okay, thanks.

**Comment by ain-soph** [comment]
Any problem still exists?
