### ISSUE TITLE
  raise RuntimeError('Dataset not found or corrupted.' + RuntimeError: Dataset not found or corrupted. You can use download=True to download it

### ISSUE THREAD

**Issue by xiaolinjieer** [ain-soph/trojanzoo#65]
**the bug**
python ./examples/train.py --color --verbose 1 --dataset cifar10 --model resnet18_comp --lr_scheduler --cutout --grad_clip 5.0 --save

it does't work because the dataset cifar10 can't be downloaded

**Comment by ain-soph** [comment]
--download

**Comment by ain-soph** [comment]
Plz close the issue if you find `--download` option makes sense.

**Comment by xiaolinjieer** [comment]
> Plz close the issue if you find `--download` option makes sense.

it works ,thanks!
