### ISSUE TITLE
AttributeError: module 'trojanvision' has no attribute 'summary'

### ISSUE THREAD

**Issue by Brownchen** [ain-soph/trojanzoo#70]
After I git clone the repo and install it, I get an attributeError When I run the scripts ‘train.py’. 
It seems like the 'summary' attribute doesn't pass correctly in ‘trojanvision/__init__.py’. 
Do you have any idea to solve the problem? Thanks!

`$ python examples/train.py --color --verbose 1 --dataset cifar10 --model resnet18_comp --lr_scheduler --cutout --grad_clip 5.0 --save
Traceback (most recent call last):
  File "/mnt/g/Cm_code/trojanzoo/examples/train.py", line 28, in <module>
    trojanvision.summary(env=env, dataset=dataset, model=model, trainer=trainer)
AttributeError: module 'trojanvision' has no attribute 'summary'`

**Comment by ain-soph** [comment]
I’m not sure how this happens, since it does import summary in trojanzoo/\_\_init\_\_.py.  

Are you using the latest version? Could you please check whether it imports trojanvision correctly? Sometime you may install an old version in your package folder.

**Comment by ain-soph** [comment]
I’ll close this issue if there is no response. I guess it’s because of old trojanzoo package version.

I’ll release a new version on pop in the near future.
