### ISSUE TITLE
use fine_pruning backdoor_defense error

### ISSUE THREAD

**Issue by soyail** [ain-soph/trojanzoo#71]
I trained the default model on MNIST dataset, and use badnet as backdoor attack method. Then I want to do backdoor defense.
First I used your example command in README.md.
`python ./examples/backdoor_defense.py --color --verbose 1 --pretrain --validate_interval 1 --dataset mnist  --attack badnet --defense neural_cleanse --random_init --epoch 50 --lr 0.01`
but it seemed to detect backdoor attack rather than backdoor defense.
Last I use fine_pruning to do backdoor defense,  the command as following:
`python ./examples/backdoor_defense.py --color --verbose 1 --pretrain --validate_interval 1 --dataset mnist --attack badnet --defense fine_pruning --random_init --epoch 50 --lr 0.01`
 it came with an error "IndexError: index 4694 is out of bounds for dimension 0 with size 64".
How can I solve it? or How can I do backdoor defense?

THANKS!
I'll appreciate it if you can answer it.

**Comment by ain-soph** [comment]
Could you provide a full log here?

For Neural Cleanse, it's generating backdoors for each class, and see if any backdoor is an outlier, which tend to be the poisoned class.

I'll investigate the fine-pruning issue.

**Comment by ain-soph** [comment]
I just test on CIFAR10 with ResNet18_comp and it works, which is the setting we use in the paper. 

I'll later check MNIST.

**Comment by soyail** [comment]
Yes, this error happened only when I test on MNIST dataset. May this message will help.

**Comment by ain-soph** [comment]
Sorry for the long delay. I'm busy doing other projects and update trojanzoo docs.
 
I've located the problem about this. The current codes assume `_model.pool` to be a `AdaptiveAvgPool2d((1,1))` that transforms tensor shape from `[N, C, H, W]` to `[N, C]`.

However, MNIST actually has a `MaxPool2d(2)` instead, it transforms `[4, 64, 24, 24]` to `[4, 64, 12, 12]`. And finally after `flatten`, the `[12, 12]` are multiplied to the channel `64`, which cause the index out of range.

<img width="628" alt="image" src="https://user-images.githubusercontent.com/13214530/155837400-fee2cd42-d248-4975-9ca4-1b1332342b58.png">

**Comment by ain-soph** [comment]
Just to note that I recently make many breaking changes. `--pretrain` to `--pretrained` and `--random_init` to `--mark_random_init` for example.

You may check the docs (have finished most part) for new apis.

https://ain-soph.github.io/trojanzoo/
