### ISSUE TITLE
[GTSRB] Type error when loading loss weights

### ISSUE THREAD

**Issue by opmusic** [ain-soph/trojanzoo#72]
When loading loss weights from GTSRB dataset, I found the default type of loss weights is np.float64, which will generate the following error:
<pre>
RuntimeError: expected scalar type Float but found Double
</pre>
And it may be fixed to add the following strict type conversion before line 182, trojanzoo/trojanzoo/models.py:
<pre>
 if (isinstance(loss_weights,np.ndarray)):
     loss_weights=np.asarray(loss_weights).astype(np.float32)
</pre>

**Comment by ain-soph** [comment]
Thanks for pointing it out. It seems this issue is introduced by new pytorch/numpy versions.

I'd prefer to keep `loss_weights` as it is and transform to float when moving to `torch.Tensor`. 

I'll draft a new release very soon.

**Comment by ain-soph** [comment]
https://github.com/ain-soph/trojanzoo/blob/7fbfb1be43531db8dc5e47ac9ddd3df824058469/trojanzoo/models.py#L182
