### ISSUE TITLE
Example train.py not work

### ISSUE THREAD

**Issue by TDteach** [ain-soph/trojanzoo#74]
I use the recommended scrip to train model on cifar10 as below:
```
python ./examples/train.py --color --verbose 1 --dataset  cifar10 --model resnet18_comp --lr_scheduler --cutout --grad_clip 5.0 --save
```
However, I get the following error
```
File "~/trojanzoo/trojanzoo/utils/model.py", line 176, in activate_params                                         
    module.requires_grad_(False)                             
AttributeError: 'ResNet' object has no attribute 'requires_grad_'
```

**Comment by TDteach** [comment]
The line-24 of ./examples/train.py 
```
model = trojanvision.models.create(...)
```
this creates an instance of Model that is different than the nn.module

And I look into the file trojanzoo/models.py
The _train function is strange as it returns 
```
return train(module=self ...)
```
obviously, self is a Model instance  that is different than the nn.module the input class of train() in trojanzoo/utils/train.py


Please correct the logic in here and fix the bug

**Comment by ain-soph** [comment]
Sorry that a recent update [9a9e1c15c2831fcf0448903c63cf73448868c09d](https://github.com/ain-soph/trojanzoo/commit/9a9e1c15c2831fcf0448903c63cf73448868c09d) introduces this issue.

**Comment by TDteach** [comment]
So, how to fix this ?

**Comment by ain-soph** [comment]
It's already fixed in the recent commits.

**Comment by ain-soph** [comment]
If you still have any trouble about this, or find my previous fix not working, please feel free to reopen this issue.
